
version: '3'

services:
  scanarr:
    build: .
    container_name: scanarr
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - ./reports:/reports
      - /media:/media:ro
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

