
version: '3'

services:
  scanarr:
    build: .
    container_name: scanarr
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - /path/to/media:/media
    restart: unless-stopped
